#!/usr/bin/env perl
use FindBin qw($RealBin);
use lib "$RealBin/lib";

use Mojolicious::Lite;
use JSON;
use Apokalo::API::Schedule;

our $api = Apokalo::API::Schedule->new;

post '/schedule' => sub {
    my $c = shift;

    my $query_params = $c->req->query_params->to_hash;

    my $code = 201;
    my $ret = eval { $api->add(%{ $query_params }) };
    if ($@) {
        $code = 400;
        my $err_msg = ref $@ eq 'Error::TypeTiny::Assertion' ? $@->message : "$@";
        chomp $err_msg;
        $err_msg =~ s/ at .+//;
        $err_msg =~ s/\(in.+args.+\{(.+)\}.+/on param $1/;

        $ret = { error => $err_msg };
    }

    $c->redirect_to($c->url_for('/schedule/' . $ret->{id})) if $code == 201;

    $c->render(
        json   => encode_json($ret),
        status => $code,
    );
};

get '/schedule/:id' => sub {
    my $c = shift;

    my $code = 200;
    my $ret = eval { $api->get( id => $c->param('id') ) };
    if ($@) {
        $code = 400;
        my $err_msg = ref $@ eq 'Error::TypeTiny::Assertion' ? $@->message : "$@";
        chomp $err_msg;
        $err_msg =~ s/ at .+//;
        $err_msg =~ s/\(in.+args.+\{(.+)\}.+/on param $1/;

        $ret = { error => $err_msg };
    }

    return $c->render( json => encode_json( {error => 'Object not found'} ), status => 404 )
      unless $ret;

    $c->render( json => encode_json($ret), status => $code );
};

get '/schedule/*' => sub {
    my $c = shift;

    $c->render( json => { error => 'Method not allowed' }, status => 405 );
};

any '/(*)' => sub {
    my $c = shift;

    $c->render( json => encode_json( {error => 'Page not found'} ), status => 404 );
};

app->max_request_size(16777216);
app->start;

